name: Build & Deploy Gatsby to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔐 Create .env.production file
        run: |
          echo "GATSBY_EMAILJS_SERVICE_ID=${{ secrets.GATSBY_EMAILJS_SERVICE_ID }}" >> .env.production
          echo "GATSBY_EMAILJS_TEMPLATE_ID=${{ secrets.GATSBY_EMAILJS_TEMPLATE_ID }}" >> .env.production
          echo "GATSBY_EMAILJS_USER_ID=${{ secrets.GATSBY_EMAILJS_USER_ID }}" >> .env.production
          echo "GATSBY_RECAPTCHA_SITE_KEY=${{ secrets.GATSBY_RECAPTCHA_SITE_KEY }}" >> .env.production
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> .env.production
          echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> .env.production

      - name: 🛠️ Build Gatsby site
        run: npm run build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
